version: "2"
run:
  concurrency: 4
  issues-exit-code: 1
  tests: true
linters:
  default: none
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - canonicalheader
    - containedctx
    - contextcheck
    - copyloopvar
    - cyclop
    - decorder
    - depguard
    - dogsled
    - dupword
    - durationcheck
    - err113
    - errcheck
    - errchkjson
    - errname
    - errorlint
    - exhaustive
    # - forbidigo  # testenvhelper needs to print to stdout
    - forcetypeassert
    - funlen
    - gochecknoinits
    - gochecksumtype
    - gocognit
    - goconst
    - gocritic
    - godot
    - godox
    - goheader
    - goprintffuncname
    - gosec
    - gosmopolitan
    - govet
    - grouper
    - importas
    - inamedparam
    - ineffassign
    - interfacebloat
    - lll
    - loggercheck
    - makezero
    - mirror
    - misspell
    - mnd
    - musttag
    - nakedret
    - nestif
    - nilerr
    - nilnil
    - noctx
    - nolintlint
    # - nonamedreturns  # Named returns used for interface compliance
    - nosprintfhostport
    # - paralleltest  # Tests can't run in parallel due to shared Google Drive state
    - perfsprint
    - prealloc
    - predeclared
    - promlinter
    - protogetter
    - reassign
    - revive
    - rowserrcheck
    - sloglint
    - spancheck
    - sqlclosecheck
    - staticcheck
    - tagalign
    - tagliatelle
    - testableexamples
    - testifylint
    - thelper
    # - tparallel  # Tests can't run in parallel due to shared Google Drive state
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - varnamelen
    - wastedassign
    - whitespace
    - wsl_v5
  settings:
    depguard:
      rules:
        prevent_unmaintained_packages:
          list-mode: lax
          files:
            - $all
            - "!$test"
          allow:
            - $gostd
          deny:
            - pkg: io/ioutil
              desc: "replaced by io and os packages since Go 1.16: https://tip.golang.org/doc/go1.16#ioutil"
    dogsled:
      max-blank-identifiers: 2
    errcheck:
      check-type-assertions: false
      check-blank: false
    funlen:
      lines: 120
      statements: 70
    gocognit:
      min-complexity: 30
    goconst:
      min-len: 3
      min-occurrences: 3
    gocritic:
      enabled-tags:
        - performance
      settings:
        captLocal:
          paramsOnly: true
        rangeValCopy:
          sizeThreshold: 32
          skipTestFuncs: true
    gocyclo:
      min-complexity: 15
    godox:
      keywords:
        - NOTE
        - OPTIMIZE
        - HACK
    govet:
      enable:
        - atomicalign
        - shadow
      enable-all: false
      disable-all: false
    lll:
      line-length: 120
      tab-width: 1
    misspell:
      locale: US
    nakedret:
      max-func-lines: 30
    prealloc:
      simple: true
      range-loops: true
      for-loops: false
    unparam:
      check-exported: false
    tagliatelle:
      case:
        rules:
          json: snake
    varnamelen:
      ignore-names:
        - err
        - ok
        - n
        - id
        - fs
        - t
        - f
      ignore-decls:
        - t testing.T
        - i int
        - j int
        - T any
    whitespace:
      multi-if: false
      multi-func: false
    cyclop:
      max-complexity: 20
  exclusions:
    generated: lax
    rules:
      - linters:
          - wsl_v5
          - mnd
          - gosec
        path: ".*"
      - linters:
          - revive
        text: "package-comments"
      - linters:
          - revive
        text: "avoid meaningless package names"
      - linters:
          - revive
        text: "avoid package names that conflict"
      - linters:
          - godot
          - godox
          - gocritic
          - sloglint
          - tagalign
          - perfsprint
          - gci
          - gochecknoglobals
          - goconst
          - lll
          - noctx
          - errchkjson
          - ineffassign
          - varnamelen
          - wastedassign
        path: ".*"
      - linters:
          - govet
        text: "shadow"
      - linters:
          - mnd
          - funlen
          - gocognit
          - gocritic
          - nestif
          - varnamelen
          - cyclop
          - thelper
        path: _test\.go
      - path: _generated\.go$
        linters:
          - all
formatters:
  enable:
    - gofmt
    - goimports
    - gci
    - gofumpt
  settings:
    gofmt:
      simplify: true
    goimports:
      local-prefixes:
        - github.com/fclairamb/afero-gdrive/
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/fclairamb/afero-gdrive/)
